---
- name: Copy the sql_exporter systemd service file
  template:
    src: sql_exporter.service.j2
    dest: /etc/systemd/system/sql_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart sql_exporter
